export const menuItemsData = [
  {
    id: 1,
    name: 'yoghurt soprole',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img1.png',
  },
  {
    id: 2,
    name: 'pan fuchs hamburguesas',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img2.png',
  },
  {
    id: 3,
    name: 'energetica monster',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img3.png',
  },
  {
    id: 4,
    name: 'manaos uva',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img4.png',
  },
  {
    id: 5,
    name: 'butterfly pasta',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img5.png',
  },
  {
    id: 6,
    name: 'Chocolate milka oreo',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img6.png',
  },
  {
    id: 7,
    name: 'Cheetos Palitos Quesos',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img7.png',
  },
  {
    id: 8,
    name: 'mantequilla soprole',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img8.png',
  },
  {
    id: 9,
    name: 'mani salado evercrisp',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img9.png',
  },
  {
    id: 10,
    name: 'papas caseras marcoPolo',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img10.png',
  },
  {
    id: 11,
    name: 'hamburguesa receta abuelo',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img11.png',
  },
  {
    id: 12,
    name: 'nugget receta abuelo',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img12.png',
  },
  {
    id: 13,
    name: 'lasagna receta abuelo',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img13.png',
  },
  {
    id: 14,
    name: 'harina montblanc',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img14.png',
  },
  {
    id: 15,
    name: 'arvejas wasil',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img15.png',
  },
  {
    id: 16,
    name: 'primavera de verduras wasil',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img16.png',
  },
  {
    id: 17,
    name: 'pure instantaneo maggi',
    info: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    price: 24,
    img: '/images/img17.png',
  },
];
